-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2022-12-03 12:44:24 GST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE admin (
    admin_id      INTEGER NOT NULL,
    admin_name    VARCHAR2(20) NOT NULL,
    password      VARCHAR2(16) NOT NULL,
    admin_picture BLOB
);

ALTER TABLE admin ADD CONSTRAINT admin_pk PRIMARY KEY ( admin_id );

CREATE TABLE agent (
    agent_id      INTEGER NOT NULL,
    agent_name    VARCHAR2(20) NOT NULL,
    commission    INTEGER,
    password      VARCHAR2(16) NOT NULL,
    salary        INTEGER NOT NULL,
    agent_picture BLOB
);

ALTER TABLE agent ADD CONSTRAINT agent_pk PRIMARY KEY ( agent_id );

CREATE TABLE in_charge_of (
    admin_admin_id INTEGER NOT NULL,
    agent_agent_id INTEGER NOT NULL
);

ALTER TABLE in_charge_of ADD CONSTRAINT in_charge_of_pk PRIMARY KEY ( admin_admin_id,
                                                                      agent_agent_id );

CREATE TABLE owned_by (
    property_property_id INTEGER NOT NULL,
    owner_owner_id       INTEGER NOT NULL,
    date_ownership       DATE
);

ALTER TABLE owned_by ADD CONSTRAINT owned_by_pk PRIMARY KEY ( property_property_id,
                                                              owner_owner_id );

CREATE TABLE owner (
    owner_id INTEGER NOT NULL,
    name     VARCHAR2(25) NOT NULL,
    phone    NUMBER(12) NOT NULL
);

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE property (
    property_id INTEGER NOT NULL,
    description VARCHAR2(100) NOT NULL,
    price       INTEGER NOT NULL,
    type        VARCHAR2(16) NOT NULL,
    p_name      VARCHAR2(16) NOT NULL,
    location    VARCHAR2(16) NOT NULL
);

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( property_id );

CREATE TABLE rent_contract (
    contract_id      INTEGER NOT NULL,
    rent_price       INTEGER NOT NULL,
    start_date       DATE NOT NULL,
    end_date         DATE NOT NULL,
    renter_renter_id INTEGER NOT NULL
);

ALTER TABLE rent_contract ADD CONSTRAINT rent_contract_pk PRIMARY KEY ( contract_id,
                                                                        renter_renter_id );

CREATE TABLE rented_by (
    property_property_id INTEGER NOT NULL,
    renter_renter_id     INTEGER NOT NULL
);

ALTER TABLE rented_by ADD CONSTRAINT rented_by_pk PRIMARY KEY ( property_property_id,
                                                                renter_renter_id );

CREATE TABLE renter (
    renter_id INTEGER NOT NULL,
    name      VARCHAR2(25) NOT NULL,
    phone     NUMBER(12) NOT NULL
);

ALTER TABLE renter ADD CONSTRAINT renter_pk PRIMARY KEY ( renter_id );

CREATE TABLE responsible_for (
    agent_agent_id       INTEGER NOT NULL,
    property_property_id INTEGER NOT NULL,
    comm_if              INTEGER
);

ALTER TABLE responsible_for ADD CONSTRAINT responsible_for_pk PRIMARY KEY ( agent_agent_id,
                                                                            property_property_id );

ALTER TABLE in_charge_of
    ADD CONSTRAINT in_charge_of_admin_fk FOREIGN KEY ( admin_admin_id )
        REFERENCES admin ( admin_id );

ALTER TABLE in_charge_of
    ADD CONSTRAINT in_charge_of_agent_fk FOREIGN KEY ( agent_agent_id )
        REFERENCES agent ( agent_id );

ALTER TABLE owned_by
    ADD CONSTRAINT owned_by_owner_fk FOREIGN KEY ( owner_owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE owned_by
    ADD CONSTRAINT owned_by_property_fk FOREIGN KEY ( property_property_id )
        REFERENCES property ( property_id );

ALTER TABLE rent_contract
    ADD CONSTRAINT rent_contract_renter_fk FOREIGN KEY ( renter_renter_id )
        REFERENCES renter ( renter_id );

ALTER TABLE rented_by
    ADD CONSTRAINT rented_by_property_fk FOREIGN KEY ( property_property_id )
        REFERENCES property ( property_id );

ALTER TABLE rented_by
    ADD CONSTRAINT rented_by_renter_fk FOREIGN KEY ( renter_renter_id )
        REFERENCES renter ( renter_id );

ALTER TABLE responsible_for
    ADD CONSTRAINT responsible_for_agent_fk FOREIGN KEY ( agent_agent_id )
        REFERENCES agent ( agent_id );

ALTER TABLE responsible_for
    ADD CONSTRAINT responsible_for_property_fk FOREIGN KEY ( property_property_id )
        REFERENCES property ( property_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
