/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cmp320project;

/**
 *
 * @author Layth (edu)
 */
public class AdminGUI extends javax.swing.JFrame {

    Admin adm = new Admin();
    

    AdminGUI(Admin admin) {
        adm.Password = admin.Password;
         adm.Picture = admin.Picture;
         adm.id = admin.id;
         adm.name = admin.name;
         initComponents();
         this.setLocationRelativeTo(null); // center form in screen 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogoutItem = new javax.swing.JMenuItem();
        ExitItem = new javax.swing.JMenuItem();
        AgentMenu = new javax.swing.JMenu();
        AddAgentItem = new javax.swing.JMenuItem();
        EditAgentItem = new javax.swing.JMenuItem();
        DeleteAgentItem = new javax.swing.JMenuItem();
        menuAssignAgent = new javax.swing.JMenuItem();
        PropertiesMenu = new javax.swing.JMenu();
        AddPropertyItem = new javax.swing.JMenuItem();
        EditPropertyItem = new javax.swing.JMenuItem();
        DeletePropertyItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        AddCustomerItem = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        EditCustomerItem = new javax.swing.JMenuItem();
        DeleteCustomerItem = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmp320project/Admin Pic.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to the Admin Portal " + adm.name + "!");

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        LogoutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        LogoutItem.setText("Logout");
        LogoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutItemActionPerformed(evt);
            }
        });
        FileMenu.add(LogoutItem);

        ExitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ExitItem.setText("Exit");
        ExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitItem);

        jMenuBar1.add(FileMenu);

        AgentMenu.setText("Agent");
        AgentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentMenuActionPerformed(evt);
            }
        });

        AddAgentItem.setText("Add Agent");
        AddAgentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAgentItemActionPerformed(evt);
            }
        });
        AgentMenu.add(AddAgentItem);

        EditAgentItem.setText("Edit Agent");
        EditAgentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAgentItemActionPerformed(evt);
            }
        });
        AgentMenu.add(EditAgentItem);

        DeleteAgentItem.setText("Delete Agent");
        DeleteAgentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAgentItemActionPerformed(evt);
            }
        });
        AgentMenu.add(DeleteAgentItem);

        menuAssignAgent.setText("Assign Agent");
        menuAssignAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAssignAgentActionPerformed(evt);
            }
        });
        AgentMenu.add(menuAssignAgent);

        jMenuBar1.add(AgentMenu);

        PropertiesMenu.setText("Properties");
        PropertiesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropertiesMenuActionPerformed(evt);
            }
        });

        AddPropertyItem.setText("Add Property");
        AddPropertyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPropertyItemActionPerformed(evt);
            }
        });
        PropertiesMenu.add(AddPropertyItem);

        EditPropertyItem.setText("Edit Property");
        EditPropertyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPropertyItemActionPerformed(evt);
            }
        });
        PropertiesMenu.add(EditPropertyItem);

        DeletePropertyItem.setText("Delete Property");
        DeletePropertyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePropertyItemActionPerformed(evt);
            }
        });
        PropertiesMenu.add(DeletePropertyItem);

        jMenuItem3.setText("Sell Property");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        PropertiesMenu.add(jMenuItem3);

        jMenuItem4.setText("Change Owner");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        PropertiesMenu.add(jMenuItem4);

        jMenuBar1.add(PropertiesMenu);

        AddCustomerItem.setText("Customers");

        jMenuItem9.setText("Add Customer");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        AddCustomerItem.add(jMenuItem9);

        EditCustomerItem.setText("Edit Customer");
        EditCustomerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCustomerItemActionPerformed(evt);
            }
        });
        AddCustomerItem.add(EditCustomerItem);

        DeleteCustomerItem.setText("Delete Customer");
        DeleteCustomerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCustomerItemActionPerformed(evt);
            }
        });
        AddCustomerItem.add(DeleteCustomerItem);

        jMenuBar1.add(AddCustomerItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitItemActionPerformed

    private void AddAgentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAgentItemActionPerformed
        // TODO add your handling code here:
        (new AddUser()).setVisible(true);
    }//GEN-LAST:event_AddAgentItemActionPerformed

    private void DeleteAgentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAgentItemActionPerformed
        // TODO add your handling code here:
        (new DeleteUser()).setVisible(true);
        
    }//GEN-LAST:event_DeleteAgentItemActionPerformed

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FileMenuActionPerformed

    private void LogoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutItemActionPerformed
        // TODO add your handling code here:
        (new LoginUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutItemActionPerformed

    private void EditAgentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAgentItemActionPerformed
        // TODO add your handling code here:
        (new EditUser()).setVisible(true);
        
    }//GEN-LAST:event_EditAgentItemActionPerformed

    private void EditCustomerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCustomerItemActionPerformed
        // TODO add your handling code here:
        (new EditCustomer()).setVisible(true);
    }//GEN-LAST:event_EditCustomerItemActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        (new AddCustomer()).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void DeleteCustomerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCustomerItemActionPerformed
        // TODO add your handling code here:
        (new DeleteCustomer()).setVisible(true);
    }//GEN-LAST:event_DeleteCustomerItemActionPerformed
    private void AddPropertyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPropertyItemActionPerformed
        // TODO add your handling code here:
        (new AddProperty()).setVisible(true);
    }//GEN-LAST:event_AddPropertyItemActionPerformed

    private void EditPropertyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPropertyItemActionPerformed
        // TODO add your handling code here:
        (new EditProperty()).setVisible(true);
    }//GEN-LAST:event_EditPropertyItemActionPerformed

    private void DeletePropertyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePropertyItemActionPerformed
        // TODO add your handling code here:
        (new DeleteProperty()).setVisible(true);
    }//GEN-LAST:event_DeletePropertyItemActionPerformed

    private void AgentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgentMenuActionPerformed

    private void PropertiesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropertiesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PropertiesMenuActionPerformed

    private void menuAssignAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAssignAgentActionPerformed
        // TODO add your handling code here:
        (new ChangeAgent()).setVisible(true);
    }//GEN-LAST:event_menuAssignAgentActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        (new EditOwner()).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        (new ChangeOwner()).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAgentItem;
    private javax.swing.JMenu AddCustomerItem;
    private javax.swing.JMenuItem AddPropertyItem;
    private javax.swing.JMenu AgentMenu;
    private javax.swing.JMenuItem DeleteAgentItem;
    private javax.swing.JMenuItem DeleteCustomerItem;
    private javax.swing.JMenuItem DeletePropertyItem;
    private javax.swing.JMenuItem EditAgentItem;
    private javax.swing.JMenuItem EditCustomerItem;
    private javax.swing.JMenuItem EditPropertyItem;
    private javax.swing.JMenuItem ExitItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem LogoutItem;
    private javax.swing.JMenu PropertiesMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuAssignAgent;
    // End of variables declaration//GEN-END:variables
}
