/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cmp320project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Layth (edu)
 */
public class AgentGUI extends javax.swing.JFrame {

    /**
     * Creates new form AgentGUI
     */
    Agent age;
    int Agentid;

    AgentGUI(Agent agent) {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        age = agent;
        Agentid=agent.id;
    }

    private AgentGUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UpdateInfoMenuItem = new javax.swing.JMenuItem();
        LogoutMenuItem = new javax.swing.JMenuItem();
        PropertyMenu = new javax.swing.JMenu();
        AssignPropMenuItem = new javax.swing.JMenuItem();
        SoldPropMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CommissionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent Menu");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmp320project/agent.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N

        UpdateInfoMenuItem.setText("Update personal information");
        UpdateInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(UpdateInfoMenuItem);

        LogoutMenuItem.setText("Logout");
        LogoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(LogoutMenuItem);

        jMenuBar1.add(jMenu1);

        PropertyMenu.setText("Property");
        PropertyMenu.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        PropertyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropertyMenuActionPerformed(evt);
            }
        });

        AssignPropMenuItem.setText("Assigned properties");
        AssignPropMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignPropMenuItemActionPerformed(evt);
            }
        });
        PropertyMenu.add(AssignPropMenuItem);

        SoldPropMenuItem.setText("Sold Properties");
        SoldPropMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldPropMenuItemActionPerformed(evt);
            }
        });
        PropertyMenu.add(SoldPropMenuItem);

        jMenuBar1.add(PropertyMenu);

        jMenu3.setText("Commission");
        jMenu3.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N

        CommissionMenuItem.setText("Show commissions");
        CommissionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommissionMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(CommissionMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoMenuItemActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            (new UpdatePersonalInfo(Agentid)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AgentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateInfoMenuItemActionPerformed

    private void LogoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuItemActionPerformed
        // TODO add your handling code here:
        (new LoginUser()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMenuItemActionPerformed

    private void SoldPropMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldPropMenuItemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            (new SoldProp(Agentid)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AgentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SoldPropMenuItemActionPerformed

    private void PropertyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropertyMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PropertyMenuActionPerformed

    private void AssignPropMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignPropMenuItemActionPerformed
        try {
            // TODO add your handling code here:
            (new AssignedProp(Agentid)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AgentGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AssignPropMenuItemActionPerformed

    private void CommissionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommissionMenuItemActionPerformed
        // TODO add your handling code here:
        (new Commission(Agentid)).setVisible(true);
    }//GEN-LAST:event_CommissionMenuItemActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AssignPropMenuItem;
    private javax.swing.JMenuItem CommissionMenuItem;
    private javax.swing.JMenuItem LogoutMenuItem;
    private javax.swing.JMenu PropertyMenu;
    private javax.swing.JMenuItem SoldPropMenuItem;
    private javax.swing.JMenuItem UpdateInfoMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
