/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cmp320project;

import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdullah Usmani
 */
public class ChangeAgent extends javax.swing.JFrame {

    /**
     * Creates new form ChangeAgent
     */
    JDBCConnection dbCon;
  ResultSet rs;
  ResultSet rsagentid;
  String OriginalID;
    /**
     * Creates new form ChangeAgent
     */
    public ChangeAgent() {
        initComponents();
        dbCon = new JDBCConnection();
        getNewData();
                this.setLocationRelativeTo(null);
    }
private void getNewData() {

        try {
            
            // populate deptno field
            rsagentid = dbCon.executeStatement("SELECT AGENT_ID FROM AGENT");
//            rsdeptno = statement.executeQuery("SELECT deptno, dname FROM dept ORDER BY deptno ASC ");
            agentidcmb.removeAllItems();
            while (rsagentid.next()) {
                agentidcmb.addItem(rsagentid.getString("AGENT_ID"));
            }

            // populate mgr field
            rs = dbCon.executeStatement("select agent_agent_id,property_id,p_name from responsible_for r,property,owned_by o where property.property_id = o.property_property_id and property.property_id = r.property_property_id and owner_owner_id = 300000001 ");
//            rs = statement.executeQuery("SELECT empno, ename, job, mgr, hiredate, sal, comm, deptno FROM emp ORDER BY empno ASC ");

            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected empno.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
private void populateFields() {
        try {
            PropIDlbl.setText(rs.getString("property_id"));
            agentidcmb.setSelectedItem(rs.getString("agent_agent_id"));
            OriginalID=rs.getString("property_id");
            PropNamelbl.setText(rs.getString("p_name"));
           
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(ChangeAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void MoveNext() {
        try {
            // TODO add your handling code here:
            if (!rs.isLast()) {
                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChangeAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {                                        
        MoveNext();
    }                                       

    private void MovePrevious() {
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChangeAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EnableDisableButtons() {
        try {
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }
            if (rs.isLast()) {
                Nextbtn.setEnabled(false);
            } else {
                Nextbtn.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChangeAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PropIDlbl = new javax.swing.JLabel();
        PropNamelbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agentidcmb = new javax.swing.JComboBox<>();
        btnPrevious = new javax.swing.JButton();
        UpdateAgentbtn = new javax.swing.JButton();
        Nextbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agent Assignment");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE ASSIGNED AGENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Property ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Property Name");

        PropIDlbl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PropIDlbl.setForeground(new java.awt.Color(0, 51, 51));
        PropIDlbl.setText("jLabel4");

        PropNamelbl.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PropNamelbl.setForeground(new java.awt.Color(0, 51, 51));
        PropNamelbl.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Agent ID");

        agentidcmb.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        agentidcmb.setForeground(new java.awt.Color(0, 51, 51));
        agentidcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPrevious.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(0, 51, 51));
        btnPrevious.setText("<<PREV");
        btnPrevious.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPrevious.setContentAreaFilled(false);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        UpdateAgentbtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        UpdateAgentbtn.setForeground(new java.awt.Color(255, 51, 51));
        UpdateAgentbtn.setText("Update Agent");
        UpdateAgentbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpdateAgentbtn.setContentAreaFilled(false);
        UpdateAgentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAgentbtnActionPerformed(evt);
            }
        });

        Nextbtn.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        Nextbtn.setForeground(new java.awt.Color(0, 51, 51));
        Nextbtn.setText("NEXT>>");
        Nextbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Nextbtn.setContentAreaFilled(false);
        Nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(PropIDlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PropNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agentidcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(UpdateAgentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PropIDlbl))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PropNamelbl))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nextbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(agentidcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(UpdateAgentbtn)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void UpdateAgentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAgentbtnActionPerformed
        // TODO add your handling code here:
        int confirm;
            confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this user?") ;
            if (confirm==0){
            try {
                String prepSQL = "UPDATE RESPONSIBLE_FOR SET AGENT_AGENT_ID = "+agentidcmb.getSelectedItem()+" where property_property_id = "+OriginalID;
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("Agent ID " + agentidcmb.getSelectedItem() + " updated successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    getNewData();

                }
                else{
                    javax.swing.JLabel label = new javax.swing.JLabel("Updated Failed");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "Failed", JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (SQLException ex) {
                Logger.getLogger(ChangeAgent.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_UpdateAgentbtnActionPerformed

    private void NextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextbtnActionPerformed
        // TODO add your handling code here:
        MoveNext();
    }//GEN-LAST:event_NextbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Nextbtn;
    private javax.swing.JLabel PropIDlbl;
    private javax.swing.JLabel PropNamelbl;
    private javax.swing.JButton UpdateAgentbtn;
    private javax.swing.JComboBox<String> agentidcmb;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
